apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  template:
    spec:
      containers:
        - name: core
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
