# Spring #
spring.application.name=tech-challenge-core
spring.output.ansi.enabled=always
spring.jpa.open-in-view=false
spring.profiles.default=dev

# Server #
server.servlet.context-path=/core
server.port=8080
spring.servlet.multipart.max-file-size=50MB

# Actuator #
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

# SpringDoc #
openapi.service.title=Tech Challenge
openapi.service.description=FIAP Tech Challenge
openapi.service.version=1.0.0
springdoc.show-actuator=true
springdoc.swagger-ui.display-request-duration=true
springdoc.pre-loading-enabled=true
springdoc.writer-with-order-by-keys=true

# Logging #
logging.level.root=ERROR
logging.level.org.springframework.boot=INFO
logging.level.com.netflix.eureka=ERROR
logging.level.com.netflix.discovery=ERROR

# Info #
info.app.version=@version@
info.gradle.version=@gradle_version@