# Database #
spring.datasource.url=${jdbc.url}
spring.datasource.username=${jdbc.username}
spring.datasource.password=${jdbc.password}
spring.datasource.driver-class-name=${jdbc.driver}
spring.jpa.properties.hibernate.dialect=${jdbc.dialect}
spring.datasource.type=${jdbc.type}

spring.datasource.hikari.pool-name=${HIKARI_POOL_NAME:tech-challenge-core-pool}
spring.datasource.hikari.idle-timeout=${HIKARI_IDLE_TIMEOUT:60000}
spring.datasource.hikari.max-lifetime=${HIKARI_MAX_LIFETIME:120000}
spring.datasource.hikari.connection-timeout=${HIKARI_CONNECTION_TIMEOUT:30000}
spring.datasource.hikari.maximum-pool-size=${HIKARI_MAXIMUM_POOL_SIZE:10}
spring.datasource.hikari.leak-detection-threshold=${HIKARI_LEAK_DETECTION_THRESHOLD:20000}

spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.show_sql=${SHOW_SQL:false}

jdbc.username=${JDBC_USERNAME:techdev}
jdbc.password=${JDBC_PASSWORD:techdevpw}
jdbc.host=${JDBC_HOST:localhost}
jdbc.port=${JDBC_PORT:5432}
jdbc.servicename=${JDBC_SERVICENAME:techbase}
jdbc.url=${JDBC_URL:jdbc:postgresql://${jdbc.host}:${jdbc.port}/${jdbc.servicename}}
jdbc.driver=${JDBC_DRIVER:org.postgresql.Driver}
jdbc.dialect=${JDBC_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
jdbc.type=${JDBC_TYPE:com.zaxxer.hikari.HikariDataSource}

# Liquibase #
spring.liquibase.contexts=dev

# Security #
jwt.public.key=${JWT_PUBLIC_KEY:classpath:certs/dev-public.pem}
jwt.private.key=${JWT_PRIVATE_KEY:classpath:certs/dev-private.pem}
jwt.expiry.duration=${JWT_EXPIRY_DURATION:1h}