apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tech-challenge-core
  ports:
    - name: http
      port: 8080
      targetPort: http
