package br.com.fiap.pos.tech_challenge.core.domain.enums;

/**
 * @author johncgo
 * @since 2026-06-24
 */
public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCESS_DENIED,
    REAUTHENTICATION_SUCCESS,
    REAUTHENTICATION_FAILED,
    OTP_INVALID_LIMIT,
    DISPUTED_CLOSURE,
    PRODUCT_RETURN,
    USER_DELETED,
    USER_ROLE_CHANGED,
    PASSWORD_CHANGED,
    PASSWORD_CHANGE_FAILED,
    LOGOUT_SUCCESS,
    BLACKLISTED_TOKEN_REJECTED
}
